language: csharp
solution: Zipix.sln

script:
  - xbuild /nologo
  - MONO_PATH=packages/NUnit.2.6.4/lib mono --debug ./packages/NUnit.Runners.*/tools/nunit-console.exe ./ZipixTest/bin/Debug/ZipixTest.dll -nologo -labels
