build:
  project: Zipix.sln
  # verbosity: detailed

# If we build on tags, the tags added by releases also trigger builds and
# releases and infinite loop.
skip_tags: true

before_build:
  - nuget restore
  - nuget install ilmerge -Version 2.14.1208 -o packages

after_build:
  - copy packages\NUnit.2.6.4\lib\nunit.framework.dll ZipixTest\bin\Debug\

test_script:
  - nunit-console /framework:net-4.5 ZipixTest\bin\Debug\ZipixTest.dll

artifacts:
  - path: Zipix\bin\Debug\ZipixStandalone.exe

deploy:
  release: Zipix-$(appveyor_build_version)
  description: 'Zipix'
  provider: GitHub
  auth_token:
    secure: Cr4ySNF6d3mWzpoIE0oPvB6tMjVEClDvFUguDWdM9RejgJqyRFXh16ZATPCufU8Q
  artifact: Zipix\bin\Debug\ZipixStandalone.exe
  draft: false
  prerelease: false
  on:
    branch: master
