build:
  project: Zipix.sln
  # verbosity: detailed

before_build:
  - nuget restore
  - nuget install ilmerge -Version 2.14.1208 -o packages

after_build:
  - copy packages\NUnit.2.6.4\lib\nunit.framework.dll ZipixTest\bin\Debug\

test_script:
  - nunit-console /framework:net-4.5 ZipixTest\bin\Debug\ZipixTest.dll
